"""STATUS: REAL loading logic, over MOCK/sample data. Loading and column
contract for the (simulated) supplier master -- the CSV itself is 3
fictional suppliers generated by scripts/generate_sample_data.py, standing
in for the real, tenant-isolated supplier-master service the case study
says already exists.

Columns, matching the case study's description of the existing supplier
master plus the token/hash fields our matcher actually needs:

  tenant_id, supplier_id, legal_name, dba_name, tin_token, tax_classification,
  address_street, address_city, address_state, address_zip,
  bank_routing_hash, bank_account_last4, bank_account_holder_name,
  status, last_updated_at

`tenant_id` is what enforces "customer data is strictly isolated" (per the
case study) at the query layer: decision/pipeline.py filters this DataFrame
down to only the requesting tenant's rows *before* candidate generation
ever runs, so a different tenant's supplier -- even one with an identical
name or the same TIN -- is never in the candidate pool at all, not merely
excluded by a downstream check.

`tin_token` and `bank_routing_hash` stand in for "TIN (encrypted at rest)"
and "bank account (encrypted)" from the prompt: in production these would be
opaque references resolved by the encrypted supplier-master service itself,
never plaintext handed to this pipeline. The prototype derives them with the
same `security.py` helpers the extractor uses, so a TIN/routing number is
comparable across the two sides without either one ever storing or logging
the raw digits.
"""

from __future__ import annotations

import pandas as pd

REQUIRED_COLUMNS = [
    "tenant_id", "supplier_id", "legal_name", "dba_name", "tin_token", "tax_classification",
    "address_street", "address_city", "address_state", "address_zip",
    "bank_routing_hash", "bank_account_last4", "bank_account_holder_name",
    "status", "last_updated_at",
]


def load_supplier_master(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(csv_path, dtype=str).fillna("")
    missing = set(REQUIRED_COLUMNS) - set(df.columns)
    if missing:
        raise ValueError(f"Supplier master is missing required columns: {sorted(missing)}")
    return df
